name: test
on:
  push:
    branches:
    - master

env:
  FIRST_NAME: Mona
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
   with:
    host: 45.130.15.51
    username: root
    password: ${{ secrets.PASSWORD }}
    port: 22
    script: 
            ls -a
            echo "test"
            exit whoami

