name: test
on:
  push:
    branches:
    - master

env:
  FIRST_NAME: Mona
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            whoami
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
          host: 45.130.15.51
          user: root
          key: ${{ secrets.SSH_KEY}}
          args: "-tt -vvv"
